### PR TITLE
Add Gemini client

### PR DESCRIPTION
**Pull request by lassik**
* I started a `(live net ...)` namespace for networking libraries, similar to https://pkg.go.dev/std has a `net/` namespace. If `net` is not a good name, we can use another.

* I added `openssl` and `uri-generic` to our Chicken dependencies.

* `openssl` is non-portable Scheme code that is hard to do without.

* `uri-generic` is good to have so we can interoperate with URI objects made by other Chicken packages. Live should probably define its own URI datatype, but that should probably re-use the most popular URI type on each Scheme implementation whenever possible.

* Gemini works in Chicken:

`scripts/reinstall-chicken-5-egg.sh`

```Scheme
(import (live net gemini unstable)
        (live net gemini client unstable))

(display (gemini-get
          "gemini://gemini.circumlunar.space/capcom/"
          (lambda (response)
            (or (gemini-response-raise response)
                (gemini-response-read-string-all response)))))
```

### CODE REVIEW

**Comment by lassik** [comment]
`read-string-all` is not a very good name

**Review by amirouche — COMMENTED** [review]
There is no tests :/

**Comment by lassik** [comment]
Should we use bytevector ports to test `read-response`?

**Comment by lassik** [comment]
`read-cr-lf-terminated-line` is generally useful and should go into some other library.

**Comment by amirouche** [comment]
I am not against the idea of repeating the same code if it helps readability. In that case, where would read-cr-lf-terminated-line make sense? maybe `(live text)`?

**Comment by lassik** [comment]
I agree that "a little copying is better than a little dependency" (Rob Pike). However, in this case it's fairly easy to avoid copying since we have all the libraries in the same collection.

`(live text)` or `(live port)`?

**Comment by lassik** [comment]
I'll merge this as-is since it works. I'll add the tests in another PR since we have a lot of stuff to do.

**Pull request merged**
